apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull-pattern
  namespace: patterns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pull-pattern
  template:
    metadata:
      labels:
        app: pull-pattern
    spec:
      containers:
      - name: pull-pattern
        image: siddharth67/gitops-visualizer:pull
        ports:
        - containerPort: 80


        