apiVersion: v1
kind: Service
metadata:
  name: highway-animation-service
spec:
  selector:
    app: highway-animation
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: NodePort 