apiVersion: v1
kind: Service
metadata:
  name: app-rollout-service
  namespace: canary
spec:
  selector:
    app: app-rollout
  ports:
    - name: http
      port: 80
      targetPort: 3311
  type: NodePort