apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: replica-count.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: highway-animation