apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: kustomize-prod
patches:
- path: replica-patch.yml
  target:
    kind: Deployment
    name: highway-animation
- path: env-patch.yml
  target:
    kind: Deployment
    name: highway-animation